name: Update Databricks Notebook and Push to GitHub

on:
  push:
    branches:
      - main

jobs:
  update_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Install Databricks CLI
      run: |
        pip install databricks-cli
        
    - name: Install compatible urllib3 and chardet versions
      run: |
        pip install urllib3==1.26.7 chardet==4.0.0

    - name: Configure Databricks CLI
      run: |
        # Create a configuration file with host and token
        cat <<EOL > $HOME/.databrickscfg
        [DEFAULT]
        host = $DATABRICKS_HOST
        token = $DATABRICKS_TOKEN
        EOL
        # Verify the configuration
        cat $HOME/.databrickscfg
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    - name: Debug Token and Host
      run: |
        echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}"
        echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}"
        
    - name: Verify Databricks CLI Configuration
      run: cat $HOME/.databrickscfg
    
    - name: Update Databricks Notebook
      run: |
        # Export and import the notebook in Databricks workspace
        databricks workspace export -o "dbfs:/FileStore/Files/ci_cd.py" "workspace:/Users/shyamkumarr@jmangroup.com/cicd"
        databricks workspace import -o "dbfs:/FileStore/Files/ci_cd.py" "workspace:/Users/shyamkumarr@jmangroup.com/cicd"

        
    - name: Configure Git and Push to GitHub
      run: |
        git config --global user.email "shyamkumarr@jmangroup.com"
        git config --global user.name "shyam2180"
        git add .
        git commit -m "Update Databricks notebook"
        git push
